### ISSUE TITLE
Doesn't open after following the steps

### ISSUE THREAD

**Issue by MrArdillo** [MatveyM11/EnvyControl-PyQt#1]
What dependencies i need for it to work?

**Comment by MatveyM11** [comment]
> What dependencies i need for it to work?

Try to install PyQt5

```terminal
pip install pyqt5
```

**Comment by InnKeepNY** [comment]
I can also confirm that this is an issue for me as well. And PyQt5 is installed. I did an installation recently and all went fine. Now nothing happens. Directly running the app creates a black screen with a plus sign cursor.

**Comment by MatveyM11** [comment]
> I can also confirm that this is an issue for me as well. And PyQt5 is installed. I did an installation recently and all went fine. Now nothing happens. Directly running the app creates a black screen with a plus sign cursor.

Can you run it please via console? Is there any errors in the output?

**Comment by MrArdillo** [comment]
> > I can also confirm that this is an issue for me as well. And PyQt5 is installed. I did an installation recently and all went fine. Now nothing happens. Directly running the app creates a black screen with a plus sign cursor.
> 
> Can you run it please via console? Is there any errors in the output?

Sure. It's in spanish but this is
./EnvyControl Qt.dekstop: línea 1: [Desktop: orden no encontrada
./EnvyControl Qt.dekstop: línea 3: `Comment[es_ES]': no es un identificador válido
./EnvyControl Qt.dekstop: línea 3: switch: orden no encontrada
./EnvyControl Qt.dekstop: línea 4: switch: orden no encontrada
/home/jorge/EnvyControl/main/envycontrol_qt.py: línea 2: from: orden no encontrada
/home/jorge/EnvyControl/main/envycontrol_qt.py: línea 4: from: orden no encontrada
/home/jorge/EnvyControl/main/envycontrol_qt.py: línea 5: from: orden no encontrada
/home/jorge/EnvyControl/main/envycontrol_qt.py: línea 7: error sintáctico cerca del elemento inesperado `('
/home/jorge/EnvyControl/main/envycontrol_qt.py: línea 7: `current_dir = os.path.dirname(os.path.abspath(__file__))'
./EnvyControl Qt.dekstop: línea 17: X-KDE-SubstituteUID=false: orden no encontrada
./EnvyControl Qt.dekstop: línea 18: X-KDE-Username=: orden no encontrada

**Comment by InnKeepNY** [comment]
here is my info
![Screenshot at 2023-03-19 05-17-49](https://user-images.githubusercontent.com/44852445/226175055-f1ce5c3b-f7c9-4d92-a362-ce99cbef6fec.png)
Just as a side note I'm using Debian but have had no issues until a recent re-install. For me PyQt5 was already installed:

pip install --break-system-packages PyQt5
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyQt5 in /usr/lib/python3/dist-packages (5.15.9)
Requirement already satisfied: PyQt5-sip<13,>=12.11 in /usr/lib/python3/dist-packages (from PyQt5) (12.11.1)

**Comment by MatveyM11** [comment]
> > > I can also confirm that this is an issue for me as well. And PyQt5 is installed. I did an installation recently and all went fine. Now nothing happens. Directly running the app creates a black screen with a plus sign cursor.
> > 
> > 
> > Can you run it please via console? Is there any errors in the output?
> 
> Sure. It's in spanish but this is ./EnvyControl Qt.dekstop: línea 1: [Desktop: orden no encontrada ./EnvyControl Qt.dekstop: línea 3: `Comment[es_ES]': no es un identificador válido ./EnvyControl Qt.dekstop: línea 3: switch: orden no encontrada ./EnvyControl Qt.dekstop: línea 4: switch: orden no encontrada /home/jorge/EnvyControl/main/envycontrol_qt.py: línea 2: from: orden no encontrada /home/jorge/EnvyControl/main/envycontrol_qt.py: línea 4: from: orden no encontrada /home/jorge/EnvyControl/main/envycontrol_qt.py: línea 5: from: orden no encontrada /home/jorge/EnvyControl/main/envycontrol_qt.py: línea 7: error sintáctico cerca del elemento inesperado `(' /home/jorge/EnvyControl/main/envycontrol_qt.py: línea 7: `current_dir = os.path.dirname(os.path.abspath(**file**))' ./EnvyControl Qt.dekstop: línea 17: X-KDE-SubstituteUID=false: orden no encontrada ./EnvyControl Qt.dekstop: línea 18: X-KDE-Username=: orden no encontrada

I'm studying in the spanish university, so don't be afraid to post in spanish.

Problem in this case is that you're trying to launch .desktop from the terminal which is not allowed, system thinks that you're running bashscript.

I fixed python script, the problem was a change of the output format by the `envycontrol -q`

**Comment by MatveyM11** [comment]
> here is my info ![Screenshot at 2023-03-19 05-17-49](https://user-images.githubusercontent.com/44852445/226175055-f1ce5c3b-f7c9-4d92-a362-ce99cbef6fec.png) Just as a side note I'm using Debian but have had no issues until a recent re-install. For me PyQt5 was already installed:
> 
> pip install --break-system-packages PyQt5 Defaulting to user installation because normal site-packages is not writeable Requirement already satisfied: PyQt5 in /usr/lib/python3/dist-packages (5.15.9) Requirement already satisfied: PyQt5-sip<13,>=12.11 in /usr/lib/python3/dist-packages (from PyQt5) (12.11.1)

Many thanks, the error was caused by the new update of the envycontrol.
In previous version `envycontrol - q` was giving output in such style - `mode: hybrid`, but now it's `hybrid\n`.

**Comment by MatveyM11** [comment]
I've remade `def start_stutus(self)` function, now the problem is gone.

```python
 def start_status(self):
        status_output = subprocess.check_output(['envycontrol', '-q']).decode().strip()
        keywords = ["hybrid", "integrated", "nvidia"]
        for keyword in keywords:
            if re.search(keyword, status_output, re.IGNORECASE):
                return keyword
        return "envycontrol -q output style was changed"
```
